if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager",repos = "http://cran.us.r-project.org")
BiocManager::install(version = "3.17",repos = "http://cran.us.r-project.org")
BiocManager::install("BgeeDB",repos = "http://cran.us.r-project.org")
BiocManager::install("BgeeCall",repos = "http://cran.us.r-project.org")